name = "fortune-telling"

[[kv_namespaces]]
binding = "LIMITS_KV"
id = "14706b06f36241e8aa4c509964637afa"   # 在控制台KV页面查看

[[kv_namespaces]]
binding = "CACHE_KV"
id = "8ce1ab7f40b546538d8edaeecc6c6e34"